core/urls.py
from django.urls import path

from core.views import HomePageView

app_name = 'core'

urlpatterns = [
    path('', HomePageView.as_view(), name='home-page'),

]

filters/urls.py
from django.urls import path

from filters.views import SearchHistoryListView

app_name = 'filters'

urlpatterns = [
    path('search-history/', SearchHistoryListView.as_view(), name='search-history'),
]

posts/urls.py
from django.urls import path

from posts.views import PostListView, PostSearchView

app_name = 'posts'

urlpatterns = [
    path('posts/', PostListView.as_view(), name='post_list'),
    path('search/', PostSearchView.as_view(), name='post_search'),
]

search_engine_qtec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
    path('', include('filters.urls', namespace='filters')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from users.views import UserLoginView, UserLogoutView, RegisterView, ProfileView

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

templates/snippets/footer.html
<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <a style="text-decoration: none;" href="https://www.github.com/milon19/">
            <span class="text-muted">Milon Mahato</span>
        </a>
        <span class="text-muted" style="float: right;">milonmahato67@gmail.com</span>
    </div>
</footer>

templates/snippets/navbar.html
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'core:home-page' %}">Django Advance Filtering</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'core:home-page' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:post_list' %}">Posts</a>
          </li>
        </ul>
        <div class="d-flex" style="margin-left: auto;">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' %}">Profile</a>
                    </li>
                {% else %}
                     <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'users:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'users:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
      </div>
    </div>
  </nav>
</header>

templates/snippets/search-history.html
<div class="container">
    <div class="row text-center m-3">
        <div class="col-12">
            <h2>Search History</h2>
        </div>
    </div>
    <div class="row" >
        <div class="col-3 p-2" style="border: 1px solid silver; border-right: 0; height: 720px; overflow: scroll;">
            <p>Apply filters: </p>
            <form action="{% url 'filters:search-history' %}" method="get" id="filter-form">
                <label><strong>Users</strong></label>
                {% if users|length < 1 %}
                    <p><small class="text-muted">No user data available...</small></p>
                {% else %}
                    <div class="form-check">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" value="None" id="none" name="username">
                            <label class="form-check-label" for="none">None</label>
                        </div>
                    </div>
                    {% for user in users %}
                        <div class="form-check">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" value="{{ user.username }}" id="{{ user.userame }}" name="username">
                                <label class="form-check-label" for="{{ user.useram }}">{{ user.username }}</label>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                <br>
                <label><strong>Keywords</strong></label>
                 {% if keywords|length < 1 %}
                    <p><small class="text-muted">No keywords data available...</small></p>
                {% endif %}
                {% for keyword in keywords %}
                    <div class="form-check">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" value="{{ keyword.keyword }}" id="{{ keyword.keyword }}" name="keyword">
                            <label class="form-check-label" for="{{ keyword.keyword }}">
                                {{ keyword.keyword }}
                                <span class="text-muted">
                                    [found {{ keyword.count }} time(s)]
                                </span>
                            </label>
                        </div>
                    </div>
                {% endfor %}
                <br>
                <label><strong>Time</strong></label>
                <div class="form-check">
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input sev_check" value="Y" id="yesterday" name="time">
                        <label class="form-check-label" for="yesterday">Yesterday</label>
                    </div>
                </div>
                <div class="form-check">
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input sev_check" value="W" id="last_week" name="time">
                        <label class="form-check-label" for="last_week">Last Week</label>
                    </div>
                </div>
                <div class="form-check">
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input sev_check" value="M" id="last_month" name="time">
                        <label class="form-check-label" for="last_month">Last Month</label>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary mt-1">Search Result</button>
            </form>
        </div>
        <div class="col-9 p-2" id="search-result-data" style="border: 1px solid silver; height: 720px; overflow: scroll;">
            <!--put data using jQuery-->
        </div>
    </div>
</div>