core/urls.py
from django.urls import path

from core.views import HomePageView

app_name = 'core'

urlpatterns = [
    path('', HomePageView.as_view(), name='home-page'),

]

posts/urls.py
from django.urls import path

from posts.views import PostListView, PostSearchView

app_name = 'posts'

urlpatterns = [
    path('posts/', PostListView.as_view(), name='post_list'),
    path('search/', PostSearchView.as_view(), name='post_search'),
]

search_engine_qtec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
    path('', include('filters.urls', namespace='filters')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Django Advance Filtering | {% block title %}{% endblock %}</title>

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
        <!--My CSS-->
        <link href="{% static 'styles.css' %}" rel="stylesheet" >

    </head>

    <body class="d-flex flex-column h-100">
        {% include 'snippets/navbar.html' %}

        <main role="main" class="flex-shrink-0">
            <div class="container-fluid py-4 mt-5">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %}
                {% block contain %}
                {% endblock %}
            </div>
        </main>


        {% include 'snippets/footer.html' %}

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js" integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ==" crossorigin="anonymous"></script>
        {% block extra_script %}

        {% endblock %}
    </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Home Page
{% endblock %}

{% block contain %}
    <div class="container text-center">
        <div class="row justify-content-center">
            <div class="col-12 col-md-10 col-lg-8">
                <form class="card card-sm" action="{% url 'posts:post_search' %}" method="get">
                    <div class="card-body row no-gutters align-items-center">
                        <div class="col-auto">
                            <i class="fas fa-search h4 text-body"></i>
                        </div>
                        <div class="col">
                            <input id="search-box" onkeyup="disableButton()" class="form-control form-control-lg form-control-borderless" type="search" name='q' placeholder="Search posts or keywords">
                        </div>

                        <div class="col-auto ml-2">
                            <button id="search-button" class="btn btn-lg btn-success" type="submit">Search</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% include 'snippets/search-history.html' %}
{% endblock %}

{% block extra_script %}
    <script>
        function disableButton() {
            document.getElementById('search-button').disabled = document.getElementById("search-box").value === "";
        }
        $(document).ready(function (){
            disableButton();

            $.ajax({
                type: "get",
                url: '/search-history/',
                dataType: "json",
                success: function(data){
                    var searchResultData = $('#search-result-data')
                    var searchData = ''
                    var json_data = JSON.parse(data)
                    if (json_data.length === 0){
                        var msg = `<p class="text-center">No Search history here. Please search above.</p>`
                        searchResultData.append(msg)
                    }
                    $.each(json_data, function (index, value) {
                        searchData =
                            `<li class="list-group-item mt-2" style="box-shadow: 0px 15px 16.83px 0.17px rgba(0, 0, 0, 0.1);">
                                <div class="media" >
                                    <div class="media-body" >
                                        <h5 class="mt-0" id="keyword">${value.keyword}</h5>
                                        Search Time: <span id="time">${moment(value.time).format("LLLL")}</span>
                                        <small style="float: right">user: <span id="author">${value.user}</span></small>
                                    </div>
                                 </div>
                             </li>`
                        searchResultData.append(searchData)
                    } )
                },
                error: function(){
                    alert("error");
                }
            });

            var filterForm = $('#filter-form');
            filterForm.submit(function (event) {
                event.preventDefault()
                var thisForm = $(this)
                $.ajax({
                    type: "get",
                    url: '/search-history/',
                    dataType: "json",
                    data: thisForm.serialize(),
                    success: function(data){
                        var searchResultData = $('#search-result-data');
                        searchResultData.html('');
                        var searchData = '';
                        var json_data = JSON.parse(data);
                        if (json_data.length === 0){
                            var msg = `<p class="text-center">No Search history here. Please search above.</p>`
                            searchResultData.append(msg)
                        }
                        $.each(json_data, function (index, value) {
                            searchData =
                                `<li class="list-group-item mt-2" style="box-shadow: 0px 15px 16.83px 0.17px rgba(0, 0, 0, 0.1);">
                                    <div class="media" >
                                        <div class="media-body" >
                                            <h5 class="mt-0" id="keyword">${value.keyword}</h5>
                                            Search Time: <span id="time">${moment(value.time).format("LLLL")}</span>
                                            <small style="float: right">user: <span id="author">${value.user}</span></small>
                                        </div>
                                     </div>
                                 </li>`
                            searchResultData.append(searchData)
                        } )
                    },
                    error: function(){
                        alert("error");
                    }
                });
            });


        });
        $(function () {
          $('.sev_check').click(function(e) {
            $('.sev_check').not(this).prop('checked', false);
          });
        });

    </script>
{% endblock %}